name: Renovate manual invoke
on:
  workflow_dispatch:
  #schedule:
  #  # The "*" (#42, asterisk) character has special semantics in YAML, so this
  #  # string has to be quoted.
  #  - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.11         # https://github.com/renovatebot/github-action/releases
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}            # Will need PAT as secret encrypted with https://app.renovatebot.com/encrypt
        env:
          LOG_LEVEL: 'debug'